name: Run changeset

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - changeset-release/main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Install modules
        run: pnpm i --no-frozen-lockfile

      - name: Check for Changeset
        if: ${{ github.event_name == 'pull_request' }}
        run: npx changeset status --since=origin/main

